# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created

name: Build docker GHCR

on: 
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: build and push the image
        run: |
          docker login --username pChocz --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . --tag ghcr.io/pchocz/squash-frontend-angular:latest
          docker push ghcr.io/pchocz/squash-frontend-angular:latest
