name: build

on: 
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Adding Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          
      - name: Install Dependencies
        run: npm install --save-dev @angular/cli@14.1.3

      - name: Build Angular App
        run: npm run build --configuration=production-pjoter1v

      - name: List Files in Distribution Directory
        run: ls -R ./dist
